### ISSUE TITLE
Use Path instead of Directory as Argument for Produce

### ISSUE THREAD

**Issue by Bibob7** [kaufland-ecommerce/esque#70]

**Comment by Bibob7** [comment]
Currently we can just pass a directory as working directory for the produce command. To also be able to work with a single file, we should pass a path.

Originally posted by @Bibob7  in #39

**Comment by swenzel** [comment]
Since the consume/produce logic without the stdin/stdout arguments requires multiple files to work properly, we cannot change the argument to accept a single file.
Maybe at a later point in time we could support archives, though.

Until then, if a single file is required one can use the stdin/stdout arguments and pipe to/from a single file. Currently this will erase any schema information in case of AVRO, though.
