### ISSUE TITLE
Refactor errors.py

### ISSUE THREAD

**Issue by garrettthomaskth** [kaufland-ecommerce/esque#86]

**Comment by swenzel** [comment]
We should also keep in mind that the return code of a program on Unix is supposed to be between 0 and 255 theoretically and 0 and 125 actually (since 126-255 is meant for shell specific return codes).  
See also https://unix.stackexchange.com/a/418802/77869

So we can't keep the current approach of encoding the exception in the return code, we just have too many of them...
